# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'

#- task: Docker@2
#  displayName: Build an image
#  inputs:
#    repository: bosch
#    command: build
#    Dockerfile: Dockerfile

- script: |
    docker build -t bosch .
    docker images
    docker images | grep bosch
    sudo docker images | grep bosch
  displayName: 'Build Bosch Docker Image'

- script: docker image ls --all
  displayName: List Docker Images

- script: dir
  workingDirectory: $(Agent.BuildDirectory)
  displayName: List contents of a folder
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snykserviceconnection'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: false
  displayName: Snyk Security Scan App
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snykserviceconnection'
    testType: 'container'
    dockerImageName: 'bosch'
    dockerfilePath: 'Dockerfile'
    monitorWhen: 'always'
    failOnIssues: false
  displayName: Snyk Security Scan Container